In [6]:
import sys
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdftypes import resolve1
import pandas as pd

In [11]:
#Note: following code will not work for encrypted PDFs.  
#If we need to accomodate encrypted PDFs then I'll need to develop a work-around
filename = 'vrs-2 w data.pdf'
fp = open(filename, 'rb')

data = []
parser = PDFParser(fp)
doc = PDFDocument(parser)
fields = resolve1(doc.catalog['AcroForm'])['Fields']
for i in fields:
    field = resolve1(i)
    name, value = field.get('T'), field.get('V')
    data.append((name,value))
    
data

[(b'RESET', None),
 (b'Employer Code', b'11111'),
 (b'Name', b'Duncan J Bell'),
 (b'Ret', /'1'),
 (b'Address', b'1234 Road Rd. Rockville, MD 20855'),
 (b'Bday', b'01/01/1985'),
 (b'Elect1', /'1'),
 (b'Ben1', /'0'),
 (b'Ben2', None),
 (b'Ben3', None),
 (b'Ben4', /'1'),
 (b'Add', /'1'),
 (b'Elect2', /'0'),
 (b'Name6', None),
 (b'Social Security Number6', None),
 (b'Address6', None),
 (b'Ben6', None),
 (b'Share %6', None),
 (b'Relationship6', None),
 (b'DOB6', None),
 (b'Name7', None),
 (b'Social Security Number7', None),
 (b'Address7', None),
 (b'Ben7', None),
 (b'Share %7', None),
 (b'Relationship7', None),
 (b'DOB7', None),
 (b'Name8', None),
 (b'Social Security Number8', None),
 (b'Address8', None),
 (b'Ben8', None),
 (b'Share %8', None),
 (b'Relationship8', None),
 (b'DOB8', None),
 (b'Name of Trust Organization1', None),
 (b'Date of Trust1', None),
 (b'Address9', None),
 (b'Ben9', None),
 (b'Share %9', None),
 (b'Trustee or Organization Executive Officer1', None),
 (b'Add1', None),
 (b'Social Security Number', b'111223333'),
 (b'Name1', b'Jessica B Cromwell'),
 (b'Social Security Number1', b'222334444'),
 (b'Address1', b'ABC St. Arlington VA 22202'),
 (b'Share %1', b'100'),
 (b'Relationship1', b'Wife'),
 (b'DOB1', b'05/05/1990'),
 (b'Name2', None),
 (b'Social Security Number2', None),
 (b'Address2', None),
 (b'Share %2', None),
 (b'Relationship2', None),
 (b'DOB2', None),
 (b'Name3', None),
 (b'Social Security Number3', None),
 (b'Address3', None),
 (b'Share %3', None),
 (b'Relationship3', None),
 (b'DOB3', None),
 (b'Name4', b'Duncan J Bell Living Trust'),
 (b'Date of Trust', b'05/10/2021'),
 (b'Address4', b'Roady Road Rd., Michael MD 20022'),
 (b'Share %4', b'50'),
 (b'Trustee or Organization Executive Officer', b'Jess Cromwell'),
 (b'Elect3', /'0'),
 (b'NameOLI', None),
 (b'Social Security NumberOLI', None),
 (b'AddressOLI', None),
 (b'BenOLI', None),
 (b'Share %OLI', None),
 (b'RelationshipOLI', None),
 (b'DOBOLI', None),
 (b'NameOLI2', None),
 (b'Social Security NumberOLI2', None),
 (b'AddressOLI2', None),
 (b'BenOLI2', None),
 (b'Share %OLI2', None),
 (b'RelationshipOLI2', None),
 (b'DOBOLI2', None),
 (b'NameOLI3', None),
 (b'Social Security NumberOLI3', None),
 (b'AddressOLI3', None),
 (b'BenOLI3', None),
 (b'Share %OLI3', None),
 (b'RelationshipOLI3', None),
 (b'DOBOLI3', None),
 (b'NameOLI4', None),
 (b'Date of TrustOLI', None),
 (b'AddressOLI4', None),
 (b'BenOLI4', None),
 (b'Share %OLI4', None),
 (b'Trustee or Organization Executive OfficerOLI', None),
 (b'AddOLI', None),
 (b'NEWBEN', None)]

In [61]:
#following code takes parsed PDF data and creates a dataframe with columns & values for PDF fields.  
#we would iterate through something like this on many PDFs to build a master database

df = pd.DataFrame()
for i in data:
    col = i[0]
    value = i[1]
    if type(col) == bytes:
        col = col.decode("utf-8")
    if type(value) == bytes:
        value = value.decode("utf-8")
    if str(value) != 'None':
        if str(value)[:1] == '/':
            value = str(value)[2:][:-1]
    df[col] = [value]
    
df

,RESET,Employer Code,Name,Ret,Address,Bday,Elect1,Ben1,Ben2,Ben3,...,RelationshipOLI3,DOBOLI3,NameOLI4,Date of TrustOLI,AddressOLI4,BenOLI4,Share %OLI4,Trustee or Organization Executive OfficerOLI,AddOLI,NEWBEN
0,None,11111,Duncan J Bell,1,"1234 Road Rd. Rockville, MD 20855",01/01/1985,1,0,None,None,...,None,None,None,None,None,None,None,None,None,None

In [10]:
resolve1(fields[1])

{'AA': {'F': <PDFObjRef:398>, 'K': <PDFObjRef:399>, 'V': <PDFObjRef:400>},
 'AP': {'N': <PDFObjRef:422>},
 'DA': b'/Verdana 9 Tf 0 g',
 'F': 4,
 'FT': /'Tx',
 'Ff': 8388608,
 'MK': {},
 'MaxLen': 5,
 'P': <PDFObjRef:250>,
 'Rect': [391.458, 673.949, 578.694, 691.596],
 'Subtype': /'Widget',
 'T': b'Employer Code',
 'TU': b'Employer Code',
 'Type': /'Annot',
 'V': b'11111'}